spring.application.name=pharmassist-auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb?currentSchema=public&serverTimezone=Asia/Kolkata

spring.datasource.username=postgres
spring.datasource.password=secret

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jpa.hibernate.ddl-auto=update


